Leverage Functional Tests
umee-network/qa-integration pull request #13
Opened 2022-09-01 17:58 UTC by rbajollari

Tests to implement:

- [ ] https://github.com/umee-network/umee/issues/1307
- [ ] https://github.com/umee-network/umee/issues/1210
- [ ] https://github.com/umee-network/umee/issues/1207
- [ ] https://github.com/umee-network/umee/issues/1208
- [ ] https://github.com/umee-network/umee/issues/1209

2022-09-02 00:32 UTC, toteki approved these changes
Looks solid.

Note that I haven't been able to test on OSX yet (applies to the repository as a whole), so this is an untested review.

For later scenarios, emphasis might be less on testing that an individual user's balance increased/decreased by the right amount after one transaction, but that the transaction can be run 10000x by a bunch of users without failing, for example. In those tests, the `self.assertEqual` lines won't be needed.

2022-09-02 04:04 UTC, khoerling commented
@toteki welcome to give this PR a spin, `make setup-chain` should work on osx now:  https://github.com/umee-network/qa-integration/pull/12

2022-09-08 15:45 UTC, adamewozniak commented
@rbajollari is this ready to be merged in?

2022-09-08 16:07 UTC, rbajollari commented
@adamewozniak Withdraw leverage tx is not working currently in my tests after all the recent updates which is causing those first two tests which were passing before hand to not anymore. I'm currently trying to figure out whats causing that but once I do this branch should be ready to merge in.

Also I'll create separate prs for the other tests.

2022-09-08 16:12 UTC, adamewozniak commented
> 

Right on, if you need a second hand lmk 😄

2022-09-09 19:29 UTC, adamewozniak requested changes
Just a few suggestions - please also merge main into this branch to make the diff smaller

2022-09-09 19:29 UTC, adamewozniak commented on internal/modules/leverage/test.py
> +BLOCKS_PER_VOTING_PERIOD = 10
Did this break any of the tests @zarazan put in for the oracle?

2022-09-09 19:29 UTC, adamewozniak commented on internal/modules/leverage/test.py
> +    def test_supply_withdraw(self):
I'd add a ref here to the GH issue describing this test

2022-09-09 19:29 UTC, adamewozniak commented on internal/modules/leverage/test.py
> +    #     for i in range(50):
Please delete this commented code

2022-09-09 19:29 UTC, adamewozniak commented on internal/modules/oracle/query.py
> +BLOCKS_PER_VOTING_PERIOD = 5
Should this be updated too?

2022-09-09 19:29 UTC, adamewozniak commented on scripts/chain/start_chain.sh
> +    | .app_state["oracle"]["params"]["vote_period"] = "10"'\
Add a comment here for why we changed this please

2022-09-11 19:47 UTC, adamewozniak approved these changes
lgtm! @rbajollari please resolve conflicts & merge

2022-09-12 12:03 UTC, merged